
package br.org.credenciadora.scg.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SCGCredenciadora", targetNamespace = "http://webservice.scg.credenciadora.org.br", wsdlLocation = "file:/mnt/work/soap_test/credenciadora.wsdl")
public class SCGCredenciadora
    extends Service
{

    private final static URL SCGCREDENCIADORA_WSDL_LOCATION;
    private final static WebServiceException SCGCREDENCIADORA_EXCEPTION;
    private final static QName SCGCREDENCIADORA_QNAME = new QName("http://webservice.scg.credenciadora.org.br", "SCGCredenciadora");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/mnt/work/soap_test/credenciadora.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCGCREDENCIADORA_WSDL_LOCATION = url;
        SCGCREDENCIADORA_EXCEPTION = e;
    }

    public SCGCredenciadora() {
        super(__getWsdlLocation(), SCGCREDENCIADORA_QNAME);
    }

    public SCGCredenciadora(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCGCREDENCIADORA_QNAME, features);
    }

    public SCGCredenciadora(URL wsdlLocation) {
        super(wsdlLocation, SCGCREDENCIADORA_QNAME);
    }

    public SCGCredenciadora(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCGCREDENCIADORA_QNAME, features);
    }

    public SCGCredenciadora(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SCGCredenciadora(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControleGarantia
     */
    @WebEndpoint(name = "controleGarantia")
    public ControleGarantia getControleGarantia() {
        return super.getPort(new QName("http://webservice.scg.credenciadora.org.br", "controleGarantia"), ControleGarantia.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControleGarantia
     */
    @WebEndpoint(name = "controleGarantia")
    public ControleGarantia getControleGarantia(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.scg.credenciadora.org.br", "controleGarantia"), ControleGarantia.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCGCREDENCIADORA_EXCEPTION!= null) {
            throw SCGCREDENCIADORA_EXCEPTION;
        }
        return SCGCREDENCIADORA_WSDL_LOCATION;
    }

}
